FROM alpine:3.24

MAINTAINER Wheeler Law <whelderwheels613@gmail.com>

RUN apk --no-cache add iptables bash redsocks tcpdump

COPY redsocks.tmpl /etc/redsocks.tmpl
COPY redsocks_redudp.tmpl /etc/redsocks_redudp.tmpl
COPY entrypoint.sh /entrypoint.sh
COPY fw.sh /fw.sh
COPY whitelist.txt /etc/redsocks-whitelist.txt

ENTRYPOINT ["/entrypoint.sh"]
